
default:
	@echo "Getting input image in local dir"
	@ls src/input.jpg

	@echo "Getting terrain mask"
	
	@echo "Getting largest square cropped image from terrain mask"
	
	@echo "Getting tilable texture from square image"

	@echo "Writing image to destination"


